### ISSUE TITLE
Logger / Limiter Compatibility Roadmap

### ISSUE THREAD

**Issue by Pheotis** [the-lockedcraft-legacy-organization/ParamnesticCure#17]
> As we support CP & RC, we will not add support for the others ourselves.
> That said, implementations of the below are nonetheless welcome via Pull Requests.

<br><br>***Projects listed as ☑ are currently supported by the `main` branch of Paramnestic!***

### Loggers:
- [x] **BEST** `HAS-API` [CoreProtect](https://www.minerealm.com/community/viewtopic.php?f=32&t=16687)
- [ ] `OPEN-SOURCE` `HAS-API` [Prism](https://github.com/AddstarMC/Prism-Bukkit/tree/master/Prism-Api/src/main/java/me/botsko/prism/api)
- [ ] `OPEN-SOURCE` [LogBlock](https://github.com/LogBlock/LogBlock/tree/master/src/main/java/de/diddiz/LogBlock)

### Limiters:
- [x] **BEST** `HAS-API` [RestrictedCreative](https://github.com/hankur/RestrictedCreative/blob/master/RestrictedCreativeAPI.java)
- [ ] `OPEN-SOURCE` [LimitedCreativeReloaded](https://gitlab.com/Zenya4/limitcreative-reloaded/tree/update)
- [ ] [StrictCreative](https://www.spigotmc.org/resources/strict-creative.71089/)
